firstName = input('First Name: ')
lastName = input('Last Name: ')
age = int(input('age : '))
town = input('Town: ')
print(f'You are {firstName} {lastName}, a {age}-years old person from {town}')
